[package]
name = "seckey"
version = "0.5.0"
authors = ["quininer kel <quininer@live.com>"]
description = "Use `memsec` protected secret memory."
repository = "https://github.com/quininer/seckey"
license = "MIT"

[dependencies]
memsec = "0.3"

[dev-dependencies]
nix = "0.7"
